-- oPERADORES ARITMÉTICOS
/*
SELECT 1 AS [TESTE];
SELECT (1+1)%2 AS [TESTE];
SELECT (5)%2 AS [TESTE];
*/

-- OPERADORES RELACIONAIS
SELECT 2>3;
SELECT 2<>3;
SELECT 2!=3;
SELECT 2 IS NOT 3;

-- OPERADORES LÓGICOS

SELECT 1==1 AND 2==2;
SELECT 1>=10 OR 1>1;